import {
  abs,
  d,
  exp,
  input,
  inv,
  log,
  sgn,
  sqrt,
  square,
} from '../trader-exprs/modules/base.ts';

const r = d;

export default [
  {
    name: `Test sgn`,
    variant: 'test-csl2-6',
    input: {
      0: { x: NaN },
      10: { x: 4 },
      50: { x: -5 },
      51: { x: 6 },
      100: { x: 0 },
      200: { x: -7 },
      300: {},
    },
    program: sgn(r(input('x'))),
    output: {
      0: { z: 0 },
      10: { z: 1 },
      50: { z: -1 },
      51: { z: 1 },
      100: { z: 0 },
      200: { z: -1 },
      300: {},
    },
  },
  {
    name: `Test abs`,
    variant: 'test-csl2-6',
    input: {
      0: { x: NaN },
      10: { x: 4 },
      50: { x: -5 },
      51: { x: 6 },
      100: { x: 0 },
      200: { x: -7 },
      300: {},
    },
    program: abs(r(input('x'))),
    output: {
      0: { z: NaN },
      10: { z: 4 },
      50: { z: 5 },
      51: { z: 6 },
      100: { z: 0 },
      200: { z: 7 },
      300: {},
    },
  },
  {
    name: `Test inv`,
    variant: 'test-csl2-6',
    input: {
      0: { x: NaN },
      10: { x: 4 },
      50: { x: -5 },
      51: { x: 6 },
      100: { x: 0 },
      200: { x: -7 },
      300: {},
    },
    program: inv(r(input('x'))),
    output: {
      0: { z: NaN },
      10: { z: 1 / 4 },
      50: { z: 1 / -5 },
      51: { z: 1 / 6 },
      100: { z: NaN },
      200: { z: 1 / -7 },
      300: {},
    },
  },
  {
    name: `Test square`,
    variant: 'test-csl2-6',
    input: {
      0: { x: NaN },
      10: { x: 4 },
      50: { x: -5 },
      51: { x: 6 },
      100: { x: 0 },
      200: { x: -7 },
      300: {},
    },
    program: square(r(input('x'))),
    output: {
      0: { z: NaN },
      10: { z: 16 },
      50: { z: 25 },
      51: { z: 36 },
      100: { z: 0 },
      200: { z: 49 },
      300: {},
    },
  },
  {
    name: `Test sqrt`,
    variant: 'test-csl2-6',
    input: {
      0: { x: NaN },
      10: { x: 4 },
      50: { x: -5 },
      51: { x: 6 },
      100: { x: 0 },
      200: { x: -7 },
      300: {},
    },
    program: sqrt(r(input('x'))),
    output: {
      0: { z: NaN },
      10: { z: 2 },
      50: { z: NaN },
      51: { z: Math.sqrt(6) },
      100: { z: 0 },
      200: { z: NaN },
      300: {},
    },
  },
  {
    name: `Test exp`,
    variant: 'test-csl2-6',
    input: {
      0: { x: NaN },
      10: { x: 4 },
      50: { x: -5 },
      51: { x: 6 },
      100: { x: 0 },
      200: { x: -7 },
      300: {},
    },
    program: exp(r(input('x'))),
    output: {
      0: { z: NaN },
      10: { z: Math.exp(4) },
      50: { z: Math.exp(-5) },
      51: { z: Math.exp(6) },
      100: { z: 1 },
      200: { z: Math.exp(-7) },
      300: {},
    },
  },
  {
    name: `Test log`,
    variant: 'test-csl2-6',
    input: {
      0: { x: NaN },
      10: { x: 4 },
      50: { x: -5 },
      51: { x: 6 },
      100: { x: 0 },
      200: { x: -7 },
      300: {},
    },
    program: log(r(input('x'))),
    output: {
      0: { z: NaN },
      10: { z: Math.log(4) },
      50: { z: NaN },
      51: { z: Math.log(6) },
      100: { z: NaN },
      200: { z: NaN },
      300: {},
    },
  },
];
